### ISSUE TITLE
REGISTRY AX_UG.OCX

### ISSUE THREAD

**Issue by benrojas01** [ggreen86/VFP-Editors#1]
Good afternoon

I can't register ax_ug.ocx, windows prevents me. I had no problems with cmax40.dll

I appreciate indications

regards

**Comment by ggreen86** [comment]
What is the message that Windows provides when you try to register the control?

________________________________
From: benrojas01 ***@***.***>
Sent: Friday, April 16, 2021 8:15 PM
To: ggreen86/VFP-Editors ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/VFP-Editors] REGISTRY AX_UG.OCX (#1)


Good afternoon

I can't register ax_ug.ocx, windows prevents me. I had no problems with cmax40.dll

I appreciate indications

regards

**Comment by HPCDupre** [comment]
Hi Mr. Green, It's been a while that I have'nt work with Visual foxpro and I noticed that I have been missing it. So trying to get the best environment development, I came accross your package wich impressed me but unfortunetly, I could not make it work. I could find a copy of the Codemax activex. I am also missimg other ocx namely bblist~1.ocx (I do not have the complete name) I think it has something to do with a grid. While opening the GKK*.APP, many of them are complaining that the system.app is missing. I could not find it anywhere.
GKKProjectManager.app and GKKSearchGlobal.app are complaining that destroyicon.prg is missing. I search inside all files and I could not find it either. Finally GKKCompare.app do not find API Library probably because foxpro is unable to open the GKKCodeLibrary.app because of the missing bblist~1.ocx .
Theres no literature as to How to install the whole thing and make it work automatically. Could you please give some advise how I should set this all up.

Thanks in advance for your advice

Claude

**Comment by Tracy-P** [comment]
The ax_ug.ocx would not register due to the side-by-side configuration is incorrect.

Looking at the manifest in the OCX, it requires Microsoft.VC80.CRT and Microsoft.VC80.MFC version 8.0.50727.6195.
My machine does not have the MFC on it for VC80.

I was able to see the PRG editor in action. I was not able to get the SCX/VCX editor to work because of the ax_ug.ocx registry problem.

**Comment by ggreen86** [comment]
Sorry for the long time for response; my time has been limited.  I have uploaded the dependencies for the ActiveX components and added guidance to the end of the README.md file on the usage.  Please see this.  If still have problems, please open a new issue.
